//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuxtEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Keybinds : global::System.Configuration.ApplicationSettingsBase {
        
        private static Keybinds defaultInstance = ((Keybinds)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Keybinds())));
        
        public static Keybinds Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<KeybindCollection xmlns:xsi=\"http://www" +
            ".w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n" +
            "  <Keybinds>\r\n    <Keybind>\r\n      <Input>\r\n        <Shift>false</Shift>\r\n      " +
            "  <Control>false</Control>\r\n        <Alt>false</Alt>\r\n        <KeyValue>Oemplus<" +
            "/KeyValue>\r\n      </Input>\r\n      <Action>ZoomIn</Action>\r\n    </Keybind>\r\n    <" +
            "Keybind>\r\n      <Input>\r\n        <Shift>false</Shift>\r\n        <Control>false</C" +
            "ontrol>\r\n        <Alt>false</Alt>\r\n        <KeyValue>Add</KeyValue>\r\n      </Inp" +
            "ut>\r\n      <Action>ZoomIn</Action>\r\n    </Keybind>\r\n    <Keybind>\r\n      <Input>" +
            "\r\n        <Shift>false</Shift>\r\n        <Control>false</Control>\r\n        <Alt>f" +
            "alse</Alt>\r\n        <KeyValue>OemMinus</KeyValue>\r\n      </Input>\r\n      <Action" +
            ">ZoomOut</Action>\r\n    </Keybind>\r\n    <Keybind>\r\n      <Input>\r\n        <Shift>" +
            "false</Shift>\r\n        <Control>false</Control>\r\n        <Alt>false</Alt>\r\n     " +
            "   <KeyValue>Subtract</KeyValue>\r\n      </Input>\r\n      <Action>ZoomOut</Action>" +
            "\r\n    </Keybind>\r\n    <Keybind>\r\n      <Input>\r\n        <Shift>false</Shift>\r\n  " +
            "      <Control>false</Control>\r\n        <Alt>false</Alt>\r\n        <KeyValue>P</K" +
            "eyValue>\r\n      </Input>\r\n      <Action>PickTile</Action>\r\n    </Keybind>\r\n    <" +
            "Keybind>\r\n      <Input>\r\n        <Shift>false</Shift>\r\n        <Control>false</C" +
            "ontrol>\r\n        <Alt>false</Alt>\r\n        <KeyValue>Insert</KeyValue>\r\n      </" +
            "Input>\r\n      <Action>InsertEntity</Action>\r\n    </Keybind>\r\n    <Keybind>\r\n    " +
            "  <Input>\r\n        <Shift>false</Shift>\r\n        <Control>false</Control>\r\n     " +
            "   <Alt>false</Alt>\r\n        <KeyValue>Delete</KeyValue>\r\n      </Input>\r\n      " +
            "<Action>DeleteEntities</Action>\r\n    </Keybind>\r\n    <Keybind>\r\n      <Input>\r\n " +
            "       <Shift>false</Shift>\r\n        <Control>true</Control>\r\n        <Alt>false" +
            "</Alt>\r\n        <KeyValue>C</KeyValue>\r\n      </Input>\r\n      <Action>Copy</Acti" +
            "on>\r\n    </Keybind>\r\n    <Keybind>\r\n      <Input>\r\n        <Shift>false</Shift>\r" +
            "\n        <Control>true</Control>\r\n        <Alt>false</Alt>\r\n        <KeyValue>V<" +
            "/KeyValue>\r\n      </Input>\r\n      <Action>Paste</Action>\r\n    </Keybind>\r\n  </Ke" +
            "ybinds>\r\n</KeybindCollection>")]
        public global::WinFormsKeybinds.KeybindCollection StageEditor {
            get {
                return ((global::WinFormsKeybinds.KeybindCollection)(this["StageEditor"]));
            }
            set {
                this["StageEditor"] = value;
            }
        }
    }
}
